#!/bin/sh


cd /tmp
rm -fr *

wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar xvfz install-tl-unx.tar.gz
cd `ls -d */`

wget https://raw.github.com/swissmanu/hsr-apf-2013/master/texlive-installation.profile

sudo ./install-tl --profile=texlive-installation.profile