#!/bin/sh

echo '######################################'
echo '#           BEFORE_INSTALL           #'
echo '#              - START -             #'
echo '######################################'

echo '---- Cleaning Temp Dir ----'
cd /tmp
rm -fr *

echo '---- Download and unzip install-tl ----'
wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar xvfz install-tl-unx.tar.gz
cd `ls -d */`

echo '---- Get install-tl profile ----'
wget https://raw.github.com/swissmanu/hsr-apf-2013/master/texlive-installation.profile

echo '---- Install texlive with install-tl ----'
sudo ./install-tl --profile=texlive-installation.profile

echo '---- Modify PATH environment variable ----'
export PATH=$PATH:/usr/local/texlive/2012/bin/i386-linux

echo '######################################'
echo '#           BEFORE_INSTALL           #'
echo '#            - FINISHED -            #'
echo '######################################'